### ISSUE TITLE
User profiles are not accessible when logged in

### ISSUE THREAD

**Issue by almereyda** [indiehosters/discourse#11]
On the instance meta.allmende.io opening my user profile

- https://meta.allmende.io/u/almereyda

sends me to

- https://meta.allmende.io/404

as

- https://meta.allmende.io/u/almereyda.json?_=1511755760265

returns a 500. What is it that the server doens't like here?

- https://meta.allmende.io/u/almereyda

works perfectly from a private tab.

**Comment by unteem** [comment]
repo moved to https://lab.libreho.st/libre.sh/compose/discourse

refer to [issue](https://lab.libreho.st/libre.sh/compose/discourse/issues/11)
