### ISSUE TITLE
Cannot get emails

### ISSUE THREAD

**Issue by ymarillet** [indiehosters/discourse#12]
Hi there,

Can anyone give a Gmail SMTP configuration ? I cannot make neither my poste.io smtp nor a test gmail account smtp working .... (I get no error anywhere, logs, http response codes, etc.) but I don't receive any mail at all ...

I am stuck at the admin account creation, so frustrating :(

**Comment by pierreozoux** [comment]
Hey,

this should help:
https://github.com/indiehosters/discourse/blob/master/scripts/install#L5-L11

let me know if it didn't
