### ISSUE TITLE
Please Update Readme

### ISSUE THREAD

**Issue by marlinhares** [indiehosters/discourse#15]
To run it on my desktop I had to execute the following before script/install

export global MAIL_USER=xxxx
export global MAIL_HOST=xxx
export global MAIL_PORT=xxx
export global MAIL_PASS=xxx
export global URL=xxx

where xxx are appropriated values for each parameter.

**Comment by pierreozoux** [comment]
We gladly accept PRs :)

**Comment by unteem** [comment]
repo moved to https://lab.libreho.st/libre.sh/compose/discourse

refer to [issue](https://lab.libreho.st/libre.sh/compose/discourse/issues/15)
