### ISSUE TITLE
New Version Problem to Install

### ISSUE THREAD

**Issue by marlinhares** [indiehosters/discourse#17]
version of the conteiner 2.2.0.beta4

When installing it gave me the error:

==================================================
+ docker-compose run app bash -c 'rake admin:create'
Starting compose-discourse_redis_1    ... done
Starting compose-discourse_postgres_1 ... done
rake aborted!
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 12.3.1. Prepending `bundle exec` to your command may solve this.
/home/discourse/discourse/config/boot.rb:11:in `<top (required)>'
/home/discourse/discourse/config/application.rb:14:in `<top (required)>'
/home/discourse/discourse/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
=================================================

to solve it, I added "bundle exec " to the second "docker-compose run" command.

But I think the real solution would be to fix in the conteiner.

**Comment by pierreozoux** [comment]
Feel free to PR ;)

**Comment by unteem** [comment]
fixed in https://github.com/libresh/compose-discourse/commit/e1dbbbdd20d3dd663533e30141f5f8a3ea95e546 thanks for the PR :p
