### ISSUE TITLE
The first thing this does is fall flat.

### ISSUE THREAD

**Issue by Leopere** [indiehosters/discourse#19]
The instructions in the README.md are incomplete.  Please finish and maintain this project because it would be wonderful if the Discourse people would ditch that stupid install script that hes so in love with why embrace docker and not really embrace docker its cute that they use it but its embarassing that they can't figure out how containers work even this late in the docker game.

```BASH
root@s:~|⇒  git clone https://github.com/indiehosters/discourse.git
Cloning into 'discourse'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 191 (delta 0), reused 0 (delta 0), pack-reused 190
Receiving objects: 100% (191/191), 37.41 KiB | 497.00 KiB/s, done.
Resolving deltas: 100% (97/97), done.
root@s:~|⇒  cd discourse
root@s:~/discourse|master ⇒  ./scripts/install
++ tr -dc _A-Z-a-z-0-9
++ head -c32
++ echo
+ PG_PASSWORD=v0i-qkzWy78r8cXKjZrre_9XY536sQiE
./scripts/install: line 5: MAIL_HOST: unbound variable
root@s:~/discourse|master ⇒  docker-compose up
WARNING: The SUBNET variable is not set. Defaulting to a blank string.
ERROR: Network lb_web declared as external, but could not be found. Please create the network manually using `docker network create lb_web` and try again.
root@s:~/discourse|master ⇒```

**Comment by pierreozoux** [comment]
Yes sorry, this project is used in the context of http://libre.sh and the script is made to be run not manually.

Do you know how to use compose or not at all? If yes, you should find your way around.

What do you think, would it be worth it to have a generic compose version?

**Comment by unteem** [comment]
repo moved to https://lab.libreho.st/libre.sh/compose/discourse

refer to [issue](https://lab.libreho.st/libre.sh/compose/discourse/issues/19)
