### ISSUE TITLE
Failed to run postgres

### ISSUE THREAD

**Issue by jamesjjk** [indiehosters/discourse#2]
The container is trying to hard link to a volume and there is a known issue boot2docker on the mac.

I believe this might be the reason for issue #1 

```
postgres_1 | The files belonging to this database system will be owned by user "postgres".
postgres_1 | This user must also own the server process.
postgres_1 | 
postgres_1 | The database cluster will be initialized with locale "en_US.utf8".
postgres_1 | The default database encoding has accordingly been set to "UTF8".
postgres_1 | The default text search configuration will be set to "english".
postgres_1 | 
postgres_1 | Data page checksums are disabled.
postgres_1 | 
postgres_1 | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1 | creating subdirectories ... initdb: could not create directory "/var/lib/postgresql/data/global": Permission denied
postgres_1 | initdb: removing contents of data directory "/var/lib/postgresql/data"
peddlercore_postgres_1 exited with code 1
```

See https://github.com/docker-library/postgres/issues/60

**Comment by pierreozoux** [comment]
Thanks for the hint, do you have a way to solve this?

**Comment by jamesjjk** [comment]
Not really, its an OSX related issue; these solutions may work:
https://github.com/docker/toolbox/issues/292

**Comment by pierreozoux** [comment]
With the new version of Docker for Mac, does it solve your issue?

**Comment by unteem** [comment]
repo moved to https://lab.libreho.st/libre.sh/compose/discourse

refer to [issue](https://lab.libreho.st/libre.sh/compose/discourse/issues/2)
