### ISSUE TITLE
Increase POP3 polling frequency

### ISSUE THREAD

**Issue by gandhiano** [indiehosters/discourse#5]
The standard Discourse has a [default POP3 polling frequency of 5 minutes](https://meta.discourse.org/t/pop3-polling-time-and-debugging/16678).

If we want to propose Discourse as a replacement to standard mailing lists (especially mailman2) then we need to get a more instant workflow.

According to the post above, this should be able to change in:

app/jobs/scheduled/poll_mailbox.rb

It should be ok as long as the polling mailbox is hosted on our own domains. To guarantee this, some logic could be added to only increase the frequency for in-house mailboxes.

**Comment by pierreozoux** [comment]
To make it proper, it would need 4h work I guess. Do you have a concrete example that is worth the effort compared to the pain of waiting 5mins?

To make it, I'd prefer to use an env like `MAILING_LIST`. If set to true, it would modify the file.

The best to do it, is to add an `entrypoint.sh` script in the [Dockerfile](https://github.com/indiehosters/docker-discourse/blob/master/Dockerfile) like you can find on the wordpress image for instance.

Actually no need to monkey patch, we would just need to render the env file into: https://github.com/discourse/discourse/blob/master/config/site_settings.yml#L581

**Comment by gandhiano** [comment]
We have several dozens of mailing lists, which I could imagine offering Discourse as a replacement, if it works properly as a replacement.

After doing some tests today, I think that solving this specific issue would still not provide an adequate workflow for a mailing list replacement. There are for example issues with getting [bulk added members to automatically watch the category](https://meta.discourse.org/t/watch-category-on-bulk-invite/21456), which would be needed for "list members" to get everything as e-mail, as expected (they could manually change later, but that should be the default behavior). As well as more tests and documentation, so that people moving from a setting to the other can understand it.

With that said, I think the polling issue is a secondary one in getting a mailing list behavior, capable of replacing mailman, working on Discourse.

**Comment by pierreozoux** [comment]
I think it is better to take it as an improvement. Not as a 1 to 1 replacement.

You could identify categories within emails, pre populate them in Discourse, migrate people and tell people that they'll automatically receive a weekly sum up of what happened on their group, plus they can watch a specific category by clicking on this button (screenshot attached). I think a lot of people would be really happy to see this feature. And for the old ones that prefer their mailing list, just click on a button and done.

**Comment by almereyda** [comment]
I propose to close this issue as mailing lists are not chat services.

Also review https://discourse.transformap.co/t/eventflow-patterns-in-uncentralizing-coopetition/374 and think processes in a circular way:

A radius turning around the centre will have the same angular velocity everywhere, but the absolute velocity differs by the distance from that centre. In that sense Loomio could be a slow centre, Discourse a more stable conversation, blogs even a little more agile and only on top of this chat and microblogging systems.

**Comment by pierreozoux** [comment]
Agreed with @almereyda we have to think in term of problem space. I close it, but you can reopen one.
